/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "on-secondary-container": "#00424e",
        "on-primary-fixed": "#2c0051",
        "surface-container-lowest": "#060e20",
        "inverse-surface": "#dae2fd",
        "surface-container-highest": "#2d3449",
        "on-primary-container": "#400071",
        "surface-container-high": "#222a3d",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-fixed": "#001f26",
        "on-tertiary-container": "#00311f",
        "on-primary-fixed-variant": "#6900b3",
        "inverse-on-surface": "#283044",
        "outline": "#988d9f",
        "primary-container": "#b76dff",
        "on-tertiary": "#003824",
        "secondary": "#4cd7f6",
        "outline-variant": "#4d4354",
        "primary": "#ddb7ff",
        "surface-tint": "#ddb7ff",
        "tertiary-container": "#00a572",
        "surface-container-low": "#131b2e",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#cfc2d6",
        "surface": "#0b1326",
        "background": "#0b1326",
        "on-error": "#690005",
        "secondary-fixed-dim": "#4cd7f6",
        "secondary-container": "#03b5d3",
        "surface-bright": "#31394d",
        "primary-fixed-dim": "#ddb7ff",
        "primary-fixed": "#f0dbff",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed": "#acedff",
        "inverse-primary": "#842bd2",
        "surface-container": "#171f33",
        "surface-variant": "#2d3449",
        "on-secondary": "#003640",
        "on-tertiary-fixed": "#002113",
        "on-surface": "#dae2fd",
        "tertiary": "#4edea3",
        "on-primary": "#490080",
        "tertiary-fixed": "#6ffbbe",
        "on-background": "#dae2fd",
        "surface-dim": "#0b1326",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#4edea3"
      },
      fontFamily: {
        "space-grotesk": ["Space Grotesk", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      spacing: {
        "section-gap": "120px",
        "gutter": "24px",
      }
    },
  },
  plugins: [],
}
